use_frameworks!

target 'MARLimitable_Example' do
  pod 'MARLimitable', :path => '../'

  target 'MARLimitable_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
